# Copyright 2019-2021 by Vegard IT GmbH, Germany, https://vegardit.com
# SPDX-License-Identifier: Apache-2.0
#
# Author: Sebastian Thomschke, Vegard IT GmbH
#
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Build

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths-ignore:
    - '**/*.md'
    - '.github/*.yml'
  pull_request:
  workflow_dispatch:
    # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/


jobs:

  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2 #https://github.com/actions/checkout

    - name: Install shellcheck
      run: sudo apt-get install -y bash shellcheck

    - name: Testing with shellcheck
      run: |
        shellcheck -V
        shellcheck -s sh -e SC2059 await-*.sh

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:         [ "ubuntu-20.04", "ubuntu-18.04" ]
        test_shell: [ "ash", "bash", "busybox", "dash", "ksh", "zsh" ]
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2 #https://github.com/actions/checkout

    - name: Install ${{ matrix.test_shell }}
      run: |
        sudo apt-get install -y bash parallel ${{ matrix.test_shell }}

    - name: Test with ${{ matrix.test_shell }}
      run: |
        bash tests/test.sh ${{ matrix.test_shell }}
