# SPDX-FileCopyrightText: © Vegard IT GmbH (https://vegardit.com) and contributors
# SPDX-FileContributor: Sebastian Thomschke, Vegard IT GmbH
# SPDX-License-Identifier: Apache-2.0
#
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Build

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths-ignore:
    - '**/*.md'
    - '.github/*.yml'
    - '.semaphore/**/*'
  pull_request:
  workflow_dispatch:
    # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

jobs:

  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3 #https://github.com/actions/checkout

    - name: Run shellcheck
      run: bash tests/run-shellcheck.sh

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:         [ "ubuntu-20.04", "ubuntu-22.04" ]
        test_shell: [ "ash", "bash", "busybox", "dash", "ksh", "zsh" ]
        include:
          - { os: macos-11, test_shell: bash }
          - { os: macos-11, test_shell: ksh }
          - { os: macos-11, test_shell: zsh }
          - { os: macos-12, test_shell: bash }
          - { os: macos-12, test_shell: ksh }
          - { os: macos-12, test_shell: zsh }
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3 #https://github.com/actions/checkout

    - name: Install ${{ matrix.test_shell }}
      run: |
        if [[ "$OSTYPE" == "darwin"* ]]; then
          brew install bash parallel ${{ matrix.test_shell }}
        else
          sudo apt-get install -y bash parallel ${{ matrix.test_shell }}
        fi

    - name: Test with ${{ matrix.test_shell }}
      continue-on-error: ${{ runner.os == 'macOS' }} # too many random hangs 
      timeout-minutes: 2
      run: |
        bash tests/run-tests.sh ${{ matrix.test_shell }}
