# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Build

on:
  push:
    paths-ignore:
    - '**/*.md'
  pull_request:

jobs:

  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2 #https://github.com/actions/checkout

    - name: Install shellcheck
      run: sudo apt-get install -y bash shellcheck

    - name: Testing with shellcheck
      run: |
        shellcheck -V
        shellcheck -s sh -e SC2059 await-*.sh

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:         [ "ubuntu-20.04", "ubuntu-18.04", "ubuntu-16.04" ]
        test_shell: [ "ash", "bash", "busybox", "dash", "ksh", "zsh" ]
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2 #https://github.com/actions/checkout

    - name: Install ${{ matrix.test_shell }}
      run: |
        sudo apt-get install -y bash parallel ${{ matrix.test_shell }}

    - name: Test with ${{ matrix.test_shell }}
      run: |
        bash tests/test.sh ${{ matrix.test_shell }}
